// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: demo.proto

package cn.jinelei.rainbow.smart.protobuf;

public final class MessageProto {
    private MessageProto() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public interface HeartBeatOrBuilder extends
            // @@protoc_insertion_point(interface_extends:cn.jinelei.rainbow.smart.protobuf.HeartBeat)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>required int32 id = 1;</code>
         */
        boolean hasId();

        /**
         * <code>required int32 id = 1;</code>
         */
        int getId();

        /**
         * <code>optional int32 next = 2;</code>
         */
        boolean hasNext();

        /**
         * <code>optional int32 next = 2;</code>
         */
        int getNext();
    }

    /**
     * Protobuf type {@code cn.jinelei.rainbow.smart.protobuf.HeartBeat}
     */
    public static final class HeartBeat extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:cn.jinelei.rainbow.smart.protobuf.HeartBeat)
            HeartBeatOrBuilder {
        private static final long serialVersionUID = 0L;

        // Use HeartBeat.newBuilder() to construct.
        private HeartBeat(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private HeartBeat() {
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }

        private HeartBeat(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 8: {
                            bitField0_ |= 0x00000001;
                            id_ = input.readInt32();
                            break;
                        }
                        case 16: {
                            bitField0_ |= 0x00000002;
                            next_ = input.readInt32();
                            break;
                        }
                        default: {
                            if (!parseUnknownField(
                                    input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return cn.jinelei.rainbow.smart.protobuf.MessageProto.internal_static_cn_jinelei_rainbow_smart_protobuf_HeartBeat_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return cn.jinelei.rainbow.smart.protobuf.MessageProto.internal_static_cn_jinelei_rainbow_smart_protobuf_HeartBeat_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            cn.jinelei.rainbow.smart.protobuf.MessageProto.HeartBeat.class, cn.jinelei.rainbow.smart.protobuf.MessageProto.HeartBeat.Builder.class);
        }

        private int bitField0_;
        public static final int ID_FIELD_NUMBER = 1;
        private int id_;

        /**
         * <code>required int32 id = 1;</code>
         */
        public boolean hasId() {
            return ((bitField0_ & 0x00000001) != 0);
        }

        /**
         * <code>required int32 id = 1;</code>
         */
        public int getId() {
            return id_;
        }

        public static final int NEXT_FIELD_NUMBER = 2;
        private int next_;

        /**
         * <code>optional int32 next = 2;</code>
         */
        public boolean hasNext() {
            return ((bitField0_ & 0x00000002) != 0);
        }

        /**
         * <code>optional int32 next = 2;</code>
         */
        public int getNext() {
            return next_;
        }

        private byte memoizedIsInitialized = -1;

        @java.lang.Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            if (!hasId()) {
                memoizedIsInitialized = 0;
                return false;
            }
            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (((bitField0_ & 0x00000001) != 0)) {
                output.writeInt32(1, id_);
            }
            if (((bitField0_ & 0x00000002) != 0)) {
                output.writeInt32(2, next_);
            }
            unknownFields.writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (((bitField0_ & 0x00000001) != 0)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(1, id_);
            }
            if (((bitField0_ & 0x00000002) != 0)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(2, next_);
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof cn.jinelei.rainbow.smart.protobuf.MessageProto.HeartBeat)) {
                return super.equals(obj);
            }
            cn.jinelei.rainbow.smart.protobuf.MessageProto.HeartBeat other = (cn.jinelei.rainbow.smart.protobuf.MessageProto.HeartBeat) obj;

            if (hasId() != other.hasId()) return false;
            if (hasId()) {
                if (getId()
                        != other.getId()) return false;
            }
            if (hasNext() != other.hasNext()) return false;
            if (hasNext()) {
                if (getNext()
                        != other.getNext()) return false;
            }
            return unknownFields.equals(other.unknownFields);
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            if (hasId()) {
                hash = (37 * hash) + ID_FIELD_NUMBER;
                hash = (53 * hash) + getId();
            }
            if (hasNext()) {
                hash = (37 * hash) + NEXT_FIELD_NUMBER;
                hash = (53 * hash) + getNext();
            }
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static cn.jinelei.rainbow.smart.protobuf.MessageProto.HeartBeat parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static cn.jinelei.rainbow.smart.protobuf.MessageProto.HeartBeat parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static cn.jinelei.rainbow.smart.protobuf.MessageProto.HeartBeat parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static cn.jinelei.rainbow.smart.protobuf.MessageProto.HeartBeat parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static cn.jinelei.rainbow.smart.protobuf.MessageProto.HeartBeat parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static cn.jinelei.rainbow.smart.protobuf.MessageProto.HeartBeat parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static cn.jinelei.rainbow.smart.protobuf.MessageProto.HeartBeat parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static cn.jinelei.rainbow.smart.protobuf.MessageProto.HeartBeat parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static cn.jinelei.rainbow.smart.protobuf.MessageProto.HeartBeat parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static cn.jinelei.rainbow.smart.protobuf.MessageProto.HeartBeat parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static cn.jinelei.rainbow.smart.protobuf.MessageProto.HeartBeat parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static cn.jinelei.rainbow.smart.protobuf.MessageProto.HeartBeat parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        @java.lang.Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(cn.jinelei.rainbow.smart.protobuf.MessageProto.HeartBeat prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code cn.jinelei.rainbow.smart.protobuf.HeartBeat}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:cn.jinelei.rainbow.smart.protobuf.HeartBeat)
                cn.jinelei.rainbow.smart.protobuf.MessageProto.HeartBeatOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return cn.jinelei.rainbow.smart.protobuf.MessageProto.internal_static_cn_jinelei_rainbow_smart_protobuf_HeartBeat_descriptor;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return cn.jinelei.rainbow.smart.protobuf.MessageProto.internal_static_cn_jinelei_rainbow_smart_protobuf_HeartBeat_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                cn.jinelei.rainbow.smart.protobuf.MessageProto.HeartBeat.class, cn.jinelei.rainbow.smart.protobuf.MessageProto.HeartBeat.Builder.class);
            }

            // Construct using cn.jinelei.rainbow.smart.protobuf.MessageProto.HeartBeat.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }

            @java.lang.Override
            public Builder clear() {
                super.clear();
                id_ = 0;
                bitField0_ = (bitField0_ & ~0x00000001);
                next_ = 0;
                bitField0_ = (bitField0_ & ~0x00000002);
                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return cn.jinelei.rainbow.smart.protobuf.MessageProto.internal_static_cn_jinelei_rainbow_smart_protobuf_HeartBeat_descriptor;
            }

            @java.lang.Override
            public cn.jinelei.rainbow.smart.protobuf.MessageProto.HeartBeat getDefaultInstanceForType() {
                return cn.jinelei.rainbow.smart.protobuf.MessageProto.HeartBeat.getDefaultInstance();
            }

            @java.lang.Override
            public cn.jinelei.rainbow.smart.protobuf.MessageProto.HeartBeat build() {
                cn.jinelei.rainbow.smart.protobuf.MessageProto.HeartBeat result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public cn.jinelei.rainbow.smart.protobuf.MessageProto.HeartBeat buildPartial() {
                cn.jinelei.rainbow.smart.protobuf.MessageProto.HeartBeat result = new cn.jinelei.rainbow.smart.protobuf.MessageProto.HeartBeat(this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) != 0)) {
                    result.id_ = id_;
                    to_bitField0_ |= 0x00000001;
                }
                if (((from_bitField0_ & 0x00000002) != 0)) {
                    result.next_ = next_;
                    to_bitField0_ |= 0x00000002;
                }
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            @java.lang.Override
            public Builder clone() {
                return super.clone();
            }

            @java.lang.Override
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.setField(field, value);
            }

            @java.lang.Override
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return super.clearField(field);
            }

            @java.lang.Override
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return super.clearOneof(oneof);
            }

            @java.lang.Override
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, java.lang.Object value) {
                return super.setRepeatedField(field, index, value);
            }

            @java.lang.Override
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.addRepeatedField(field, value);
            }

            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof cn.jinelei.rainbow.smart.protobuf.MessageProto.HeartBeat) {
                    return mergeFrom((cn.jinelei.rainbow.smart.protobuf.MessageProto.HeartBeat) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(cn.jinelei.rainbow.smart.protobuf.MessageProto.HeartBeat other) {
                if (other == cn.jinelei.rainbow.smart.protobuf.MessageProto.HeartBeat.getDefaultInstance()) return this;
                if (other.hasId()) {
                    setId(other.getId());
                }
                if (other.hasNext()) {
                    setNext(other.getNext());
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            @java.lang.Override
            public final boolean isInitialized() {
                return hasId();
            }

            @java.lang.Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                cn.jinelei.rainbow.smart.protobuf.MessageProto.HeartBeat parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (cn.jinelei.rainbow.smart.protobuf.MessageProto.HeartBeat) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private int bitField0_;

            private int id_;

            /**
             * <code>required int32 id = 1;</code>
             */
            public boolean hasId() {
                return ((bitField0_ & 0x00000001) != 0);
            }

            /**
             * <code>required int32 id = 1;</code>
             */
            public int getId() {
                return id_;
            }

            /**
             * <code>required int32 id = 1;</code>
             */
            public Builder setId(int value) {
                bitField0_ |= 0x00000001;
                id_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>required int32 id = 1;</code>
             */
            public Builder clearId() {
                bitField0_ = (bitField0_ & ~0x00000001);
                id_ = 0;
                onChanged();
                return this;
            }

            private int next_;

            /**
             * <code>optional int32 next = 2;</code>
             */
            public boolean hasNext() {
                return ((bitField0_ & 0x00000002) != 0);
            }

            /**
             * <code>optional int32 next = 2;</code>
             */
            public int getNext() {
                return next_;
            }

            /**
             * <code>optional int32 next = 2;</code>
             */
            public Builder setNext(int value) {
                bitField0_ |= 0x00000002;
                next_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional int32 next = 2;</code>
             */
            public Builder clearNext() {
                bitField0_ = (bitField0_ & ~0x00000002);
                next_ = 0;
                onChanged();
                return this;
            }

            @java.lang.Override
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            @java.lang.Override
            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:cn.jinelei.rainbow.smart.protobuf.HeartBeat)
        }

        // @@protoc_insertion_point(class_scope:cn.jinelei.rainbow.smart.protobuf.HeartBeat)
        private static final cn.jinelei.rainbow.smart.protobuf.MessageProto.HeartBeat DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new cn.jinelei.rainbow.smart.protobuf.MessageProto.HeartBeat();
        }

        public static cn.jinelei.rainbow.smart.protobuf.MessageProto.HeartBeat getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        @java.lang.Deprecated
        public static final com.google.protobuf.Parser<HeartBeat>
                PARSER = new com.google.protobuf.AbstractParser<HeartBeat>() {
            @java.lang.Override
            public HeartBeat parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new HeartBeat(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<HeartBeat> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<HeartBeat> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public cn.jinelei.rainbow.smart.protobuf.MessageProto.HeartBeat getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_cn_jinelei_rainbow_smart_protobuf_HeartBeat_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_cn_jinelei_rainbow_smart_protobuf_HeartBeat_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        java.lang.String[] descriptorData = {
                "\n\ndemo.proto\022!cn.jinelei.rainbow.smart.p" +
                        "rotobuf\"%\n\tHeartBeat\022\n\n\002id\030\001 \002(\005\022\014\n\004next" +
                        "\030\002 \001(\005B\016B\014MessageProto"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        }, assigner);
        internal_static_cn_jinelei_rainbow_smart_protobuf_HeartBeat_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_cn_jinelei_rainbow_smart_protobuf_HeartBeat_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_cn_jinelei_rainbow_smart_protobuf_HeartBeat_descriptor,
                new java.lang.String[]{"Id", "Next",});
    }

    // @@protoc_insertion_point(outer_class_scope)
}
